name: Release UPRT Rescue 
on: [workflow_dispatch]
jobs:
  mkalt:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pyinstaller --onefile uprt_rescue.py
        echo 1 > "status.txt"
    - name: Commit & Push
      uses: actions-x/commit@v2
      with:
          email: noreply@example.com
          name: Update bot
          branch: main
          message: Update alt lists
